# Generated by Django 5.0.6 on 2026-07-24 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersubscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=60)),
                ('model_name', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT')], max_length=16)),
                ('fuel', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG')], max_length=16)),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('bus', 'Bus'), ('truck', 'Truck'), ('coupe', 'Coupé'), ('wagon', 'Wagon'), ('van', 'Van'), ('other', 'Other')], max_length=16)),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('engine_size', models.CharField(blank=True, max_length=20)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('duty_paid', models.BooleanField(default=False)),
                ('vin', models.CharField(blank=True, max_length=32)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='marketplace.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
