# Generated by Django 5.0.6 on 2026-10-02 11:03

import apps.deliveries.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("center_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("center_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("radius_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=14)),
                ("per_km", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "per_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=14
                    ),
                ),
                ("min_fare", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "zone_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DispatchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.200"),
                        help_text="Platform share of each fee (0.2 = 20%).",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("0.9")),
                        ],
                    ),
                ),
                (
                    "default_base_fare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("800"), max_digits=14
                    ),
                ),
                (
                    "default_per_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("150"), max_digits=14
                    ),
                ),
                (
                    "default_per_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=14
                    ),
                ),
                (
                    "default_min_fare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1200"), max_digits=14
                    ),
                ),
                (
                    "free_weight_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5"), max_digits=6
                    ),
                ),
                (
                    "road_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.30"),
                        help_text="Road distance ≈ straight line × this.",
                        max_digits=5,
                    ),
                ),
                (
                    "round_to",
                    models.PositiveIntegerField(
                        default=50, help_text="Round fees up to this many naira."
                    ),
                ),
                ("auto_surge_enabled", models.BooleanField(default=True)),
                (
                    "max_surge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.50"), max_digits=5
                    ),
                ),
                (
                    "search_radius_km",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("5.0"), max_digits=5
                    ),
                ),
                (
                    "radius_step_km",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("5.0"), max_digits=5
                    ),
                ),
                ("max_rounds", models.PositiveSmallIntegerField(default=4)),
                (
                    "offer_batch",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Riders offered at once."
                    ),
                ),
                ("offer_timeout_s", models.PositiveSmallIntegerField(default=45)),
                (
                    "location_fresh_min",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Ignore riders whose last location is older.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dispatch settings",
                "verbose_name_plural": "Dispatch settings",
            },
        ),
        migrations.CreateModel(
            name="DeliveryRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=apps.deliveries.models._reference,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("pickup_address", models.CharField(max_length=255)),
                ("pickup_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pickup_contact_name", models.CharField(blank=True, max_length=120)),
                ("pickup_contact_phone", models.CharField(blank=True, max_length=20)),
                ("pickup_note", models.CharField(blank=True, max_length=255)),
                ("dropoff_address", models.CharField(max_length=255)),
                ("dropoff_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("dropoff_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("recipient_name", models.CharField(max_length=120)),
                ("recipient_phone", models.CharField(max_length=20)),
                ("dropoff_note", models.CharField(blank=True, max_length=255)),
                ("package_description", models.CharField(max_length=255)),
                (
                    "package_category",
                    models.CharField(
                        choices=[
                            ("documents", "Documents"),
                            ("small", "Small parcel"),
                            ("medium", "Medium parcel"),
                            ("large", "Large item"),
                            ("food", "Food"),
                            ("fragile", "Fragile"),
                        ],
                        default="small",
                        max_length=10,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=6
                    ),
                ),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=7)),
                ("duration_min", models.PositiveIntegerField(default=0)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=14)),
                ("distance_fare", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "weight_fare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "zone_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=5
                    ),
                ),
                (
                    "category_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=5
                    ),
                ),
                (
                    "surge_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=5
                    ),
                ),
                ("fee", models.DecimalField(decimal_places=2, max_digits=14)),
                ("rider_payout", models.DecimalField(decimal_places=2, max_digits=14)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Finding a rider"),
                            ("accepted", "Rider on the way to pickup"),
                            ("picked_up", "Picked up"),
                            ("in_transit", "On the way"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Awaiting payment"),
                            ("paid", "Paid (held)"),
                            ("settled", "Settled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=8,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wallet", "OAM wallet"),
                            ("card", "Card / bank (Flutterwave)"),
                        ],
                        default="wallet",
                        max_length=6,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Card checkout reference (tx_ref).",
                        max_length=40,
                    ),
                ),
                ("payment_url", models.URLField(blank=True, max_length=500)),
                ("payment_provider", models.CharField(blank=True, max_length=20)),
                (
                    "delivery_code",
                    models.CharField(
                        default=apps.deliveries.models._code,
                        help_text="Given to the recipient; the rider enters it to complete.",
                        max_length=4,
                    ),
                ),
                ("proof_photo_url", models.URLField(blank=True, max_length=500)),
                ("dispatch_round", models.PositiveSmallIntegerField(default=0)),
                (
                    "dispatch_exhausted",
                    models.BooleanField(
                        default=False, help_text="No rider accepted after all rounds."
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("in_transit_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=200)),
                ("cancelled_by", models.CharField(blank=True, max_length=10)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.CharField(blank=True, max_length=300)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="deliveries.deliveryzone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Finding a rider"),
                            ("accepted", "Rider on the way to pickup"),
                            ("picked_up", "Picked up"),
                            ("in_transit", "On the way"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("actor", models.CharField(blank=True, max_length=10)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="deliveries.deliveryrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bicycle", "Bicycle"),
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("van", "Van"),
                        ],
                        default="motorcycle",
                        max_length=12,
                    ),
                ),
                ("vehicle_plate", models.CharField(blank=True, max_length=20)),
                (
                    "vehicle_description",
                    models.CharField(
                        blank=True, help_text="e.g. Red Bajaj Boxer", max_length=80
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("review_note", models.CharField(blank=True, max_length=300)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "availability",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        db_index=True,
                        default="offline",
                        max_length=8,
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("completed_deliveries", models.PositiveIntegerField(default=0)),
                (
                    "rating_avg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=3
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("id_card", "Government ID"),
                            ("license", "Driver's / rider's licence"),
                            ("vehicle", "Vehicle papers"),
                            ("selfie", "Selfie with ID"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="deliveries.riderprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.PositiveSmallIntegerField(default=1)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offered", "Offered"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("withdrawn", "Taken by another rider"),
                        ],
                        db_index=True,
                        default="offered",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="deliveries.deliveryrequest",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="deliveries.riderprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("rider_payout", models.DecimalField(decimal_places=2, max_digits=14)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("settled", "Settled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="held",
                        max_length=8,
                    ),
                ),
                ("ledger_reference", models.CharField(max_length=40)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="deliveries.deliveryrequest",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="deliveries.riderprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="deliveries.riderprofile",
            ),
        ),
        migrations.CreateModel(
            name="SurgePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="e.g. Rain, Friday rush", max_length=120
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surges",
                        to="deliveries.deliveryzone",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.AddIndex(
            model_name="riderprofile",
            index=models.Index(
                fields=["verification_status", "availability"],
                name="dlv_rider_avail_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoffer",
            constraint=models.UniqueConstraint(
                fields=("delivery", "rider"), name="dlv_offer_once"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(
                fields=["status", "payment_status"], name="dlv_status_pay_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(
                fields=["customer", "-created_at"], name="dlv_customer_idx"
            ),
        ),
    ]
