# Generated by Django 5.0.6 on 2026-10-04 03:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytransaction",
            name="commission_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverytransaction",
            name="payout_reference",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="deliverytransaction",
            name="payout_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("wallet", "Kept in OAM wallet"),
                    ("processing", "Bank transfer processing"),
                    ("sent", "Sent to bank"),
                    ("failed", "Transfer failed — in wallet"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dispatchsettings",
            name="cash_debt_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10000"),
                help_text="Riders owing more than this get no cash jobs.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="dispatchsettings",
            name="cash_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dispatchsettings",
            name="oam_account_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="dispatchsettings",
            name="oam_account_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="dispatchsettings",
            name="oam_bank_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="auto_payout",
            field=models.BooleanField(
                default=True, help_text="Send each delivery's earnings to the bank."
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="cash_commission_due",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="OAM's share of cash deliveries not yet remitted.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="payout_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="payouts.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wallet", "OAM wallet"),
                    ("card", "Card / bank (Flutterwave)"),
                    ("cash", "Cash to rider"),
                ],
                default="wallet",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Awaiting payment"),
                    ("paid", "Paid (held)"),
                    ("settled", "Settled"),
                    ("refunded", "Refunded"),
                    ("cash", "Cash on delivery"),
                ],
                db_index=True,
                default="unpaid",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="deliverytransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("held", "Held"),
                    ("settled", "Settled"),
                    ("refunded", "Refunded"),
                    ("cash_due", "Cash collected — commission due"),
                ],
                db_index=True,
                default="held",
                max_length=8,
            ),
        ),
    ]
