# Generated by Django 5.0.6 on 2026-10-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_rider_payouts_cash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("wallet", "OAM wallet"),
                    ("card", "Card / bank (Flutterwave)"),
                    ("cash", "Cash at pickup"),
                    ("on_delivery", "Pay on delivery (card, transfer or cash)"),
                ],
                default="wallet",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Awaiting payment"),
                    ("paid", "Paid (held)"),
                    ("settled", "Settled"),
                    ("refunded", "Refunded"),
                    ("cash", "Cash on delivery"),
                    ("due", "Pay on delivery"),
                ],
                db_index=True,
                default="unpaid",
                max_length=8,
            ),
        ),
    ]
