# Generated by Django 5.0.6 on 2026-08-02 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('cable', 'Cable TV')], max_length=20)),
                ('account_identifier', models.CharField(max_length=64)),
                ('biller_code', models.CharField(blank=True, max_length=64)),
                ('biller_name', models.CharField(blank=True, max_length=120)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('last_used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'beneficiaries',
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'service_type', '-last_used_at'], name='beneficiari_user_id_de6e36_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='beneficiary',
            constraint=models.UniqueConstraint(fields=('user', 'service_type', 'account_identifier'), name='uniq_user_service_identifier'),
        ),
    ]
