# Generated by Django 5.0.6 on 2026-07-03 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(default='NG', max_length=2)),
                ('category', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('cable', 'Cable TV')], max_length=16)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('cable', 'Cable TV')], max_length=16)),
                ('recipient', models.CharField(max_length=64)),
                ('plan_code', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('pay_with', models.CharField(choices=[('wallet', 'Wallet'), ('card', 'Card')], default='wallet', max_length=8)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=160, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=12)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='biller',
            constraint=models.UniqueConstraint(fields=('country', 'category', 'code'), name='uniq_biller_country_category_code'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='biller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.biller'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billorder',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_orders', to='wallet.wallet'),
        ),
        migrations.AddIndex(
            model_name='billorder',
            index=models.Index(fields=['user', 'status'], name='billing_bil_user_id_0ffd36_idx'),
        ),
        migrations.AddIndex(
            model_name='billorder',
            index=models.Index(fields=['category', 'status'], name='billing_bil_categor_5f2c5f_idx'),
        ),
    ]
