# Generated by Django 5.0.6 on 2026-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billorder',
            name='cost_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='billorder',
            name='revenue_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
