# Generated by Django 5.0.6 on 2026-07-05 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billorder_cost_amount_billorder_revenue_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='billorder',
            name='meter_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='billorder',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='billorder',
            name='units',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CustomerVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=40)),
                ('customer_id', models.CharField(max_length=64)),
                ('variation', models.CharField(blank=True, max_length=16)),
                ('customer_name', models.CharField(max_length=160)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'service_id', 'customer_id'], name='billing_cus_user_id_33769e_idx')],
            },
        ),
    ]
