# Generated by Django 5.0.6 on 2026-07-18 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billorder_customer_name_billorder_meter_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCheckout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(default='NG', max_length=2)),
                ('category', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=40)),
                ('recipient', models.CharField(max_length=64)),
                ('plan_code', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('funding_reference', models.CharField(db_index=True, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('payment_received', 'Payment received'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('bill_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_checkout', to='billing.billorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
