# Generated by Django 5.0.6 on 2026-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_cardcheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcheckout',
            name='meter_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
