# Generated by Django 5.0.6 on 2026-07-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_cardcheckout_meter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcheckout',
            name='verification_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
