# Generated by Django 5.0.6 on 2026-06-29 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('flights', 'Flights'), ('carhire', 'Carhire'), ('hotels', 'Hotels'), ('delivery', 'Delivery'), ('remittance', 'Remittance')], max_length=20)),
                ('provider', models.CharField(max_length=40)),
                ('program', models.CharField(max_length=60)),
                ('target_url', models.URLField(max_length=1000)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('clicked', 'Clicked'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='clicked', max_length=12)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('commission_currency', models.CharField(blank=True, max_length=3)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'status'], name='affiliates__categor_b2b220_idx'), models.Index(fields=['provider', 'created_at'], name='affiliates__provide_c42f58_idx')],
            },
        ),
    ]
