# Generated by Django 5.0.6 on 2026-09-29 23:48

import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("cv_url", models.URLField(blank=True, max_length=500)),
                ("cv_filename", models.CharField(blank=True, max_length=200)),
                ("cv_updated_at", models.DateTimeField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of skill names, as the candidate typed them.",
                    ),
                ),
                (
                    "skills_text",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Normalised, space-joined skills (search + matching).",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(60)],
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry level"),
                            ("mid", "Mid level"),
                            ("senior", "Senior"),
                            ("lead", "Lead / Manager"),
                            ("executive", "Executive"),
                        ],
                        max_length=12,
                    ),
                ),
                ("experience", models.JSONField(blank=True, default=list)),
                ("education", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{linkedin, github, portfolio}",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("desired_titles", models.JSONField(blank=True, default=list)),
                ("desired_categories", models.JSONField(blank=True, default=list)),
                ("desired_location_types", models.JSONField(blank=True, default=list)),
                (
                    "desired_employment_types",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "desired_salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "desired_salary_currency",
                    models.CharField(default="NGN", max_length=3),
                ),
                (
                    "desired_salary_period",
                    models.CharField(
                        choices=[
                            ("hour", "per hour"),
                            ("day", "per day"),
                            ("month", "per month"),
                            ("year", "per year"),
                        ],
                        default="month",
                        max_length=8,
                    ),
                ),
                ("willing_to_relocate", models.BooleanField(default=False)),
                ("open_to_work", models.BooleanField(default=True)),
                (
                    "is_searchable",
                    models.BooleanField(
                        default=True,
                        help_text="Visible to employers searching the candidate database.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("last_message_preview", models.CharField(blank=True, max_length=140)),
                ("employer_last_read_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_last_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to="jobs.candidateprofile",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("attachment", "Attachment"),
                            ("system", "System"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(blank=True, max_length=4000)),
                ("attachment_url", models.URLField(blank=True, max_length=500)),
                ("attachment_name", models.CharField(blank=True, max_length=200)),
                (
                    "attachment_type",
                    models.CharField(blank=True, help_text="MIME type", max_length=100),
                ),
                ("attachment_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        help_text="Client-generated id for optimistic UI de-duplication",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="jobs.chatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("technology", "Technology"),
                            ("engineering", "Engineering"),
                            ("finance", "Finance & Accounting"),
                            ("sales", "Sales & Business Development"),
                            ("marketing", "Marketing & Communications"),
                            ("design", "Design & Creative"),
                            ("operations", "Operations & Logistics"),
                            ("customer_service", "Customer Service"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education & Training"),
                            ("hospitality", "Hospitality & Travel"),
                            ("admin", "Administration"),
                            ("legal", "Legal"),
                            ("hr", "Human Resources"),
                            ("trades", "Skilled Trades & Artisans"),
                            ("driving", "Driving & Delivery"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Just me"),
                            ("2-10", "2–10"),
                            ("11-50", "11–50"),
                            ("51-200", "51–200"),
                            ("201-1000", "201–1,000"),
                            ("1000+", "1,000+"),
                        ],
                        max_length=10,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("headquarters", models.CharField(blank=True, max_length=120)),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="ISO-3166 alpha-2", max_length=2
                    ),
                ),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                ("cover_url", models.URLField(blank=True, max_length=500)),
                (
                    "brand_color",
                    models.CharField(
                        blank=True, help_text="Hex, e.g. #0F766E", max_length=7
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=12,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, help_text="e.g. CAC RC number", max_length=60
                    ),
                ),
                (
                    "verification_document_url",
                    models.URLField(blank=True, max_length=500),
                ),
                ("verification_note", models.CharField(blank=True, max_length=255)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.AddField(
            model_name="chatthread",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_threads",
                to="jobs.employerprofile",
            ),
        ),
        migrations.CreateModel(
            name="CandidateProfileView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_views",
                        to="jobs.candidateprofile",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_views",
                        to="jobs.employerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "expiry_reminder_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "employer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="jobs.employerprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=14,
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("one_click", "1-click apply"),
                            ("form", "Full application"),
                            ("invited", "Invited by employer"),
                        ],
                        default="one_click",
                        max_length=10,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, max_length=5000)),
                (
                    "cv_url",
                    models.URLField(
                        blank=True,
                        help_text="CV snapshot at apply time",
                        max_length=500,
                    ),
                ),
                ("answers", models.JSONField(blank=True, default=list)),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "match_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("match_details", models.JSONField(blank=True, default=dict)),
                (
                    "employer_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("employer_notes", models.TextField(blank=True)),
                ("interview_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("viewed_by_employer_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatthread",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread",
                to="jobs.jobapplication",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=14)),
                ("to_status", models.CharField(max_length=14)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobListing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField()),
                ("responsibilities", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("skills_text", models.TextField(blank=True, editable=False)),
                (
                    "screening_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, question, required}] asked at apply time.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("engineering", "Engineering"),
                            ("finance", "Finance & Accounting"),
                            ("sales", "Sales & Business Development"),
                            ("marketing", "Marketing & Communications"),
                            ("design", "Design & Creative"),
                            ("operations", "Operations & Logistics"),
                            ("customer_service", "Customer Service"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education & Training"),
                            ("hospitality", "Hospitality & Travel"),
                            ("admin", "Administration"),
                            ("legal", "Legal"),
                            ("hr", "Human Resources"),
                            ("trades", "Skilled Trades & Artisans"),
                            ("driving", "Driving & Delivery"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=24,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        max_length=12,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry level"),
                            ("mid", "Mid level"),
                            ("senior", "Senior"),
                            ("lead", "Lead / Manager"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=12,
                    ),
                ),
                ("min_years_experience", models.PositiveSmallIntegerField(default=0)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("on_site", "On-site"),
                        ],
                        default="on_site",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="NGN", max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[
                            ("hour", "per hour"),
                            ("day", "per day"),
                            ("month", "per month"),
                            ("year", "per year"),
                        ],
                        default="month",
                        max_length=8,
                    ),
                ),
                ("salary_visible", models.BooleanField(default=True)),
                (
                    "apply_method",
                    models.CharField(
                        choices=[
                            ("in_app", "Apply on OAM"),
                            ("external", "External website"),
                        ],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                ("external_apply_url", models.URLField(blank=True, max_length=500)),
                ("openings", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("featured_until", models.DateTimeField(blank=True, null=True)),
                ("is_boosted", models.BooleanField(default=False)),
                ("boosted_until", models.DateTimeField(blank=True, null=True)),
                (
                    "posted_with_credit",
                    models.BooleanField(
                        default=False,
                        help_text="Published using a pay-per-job credit (doesn't count against the plan's active-job limit).",
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                ("moderation_note", models.CharField(blank=True, max_length=255)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.employerprofile",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate"),
                            ("suspicious", "Suspicious content"),
                            ("reported", "Reported by user"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "related_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="jobs.joblisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.joblisting",
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_threads",
                to="jobs.joblisting",
            ),
        ),
        migrations.CreateModel(
            name="JobPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("plan", "Subscription plan"),
                            ("job_credit", "Pay-per-job credits"),
                            ("boost", "Listing boost"),
                        ],
                        max_length=12,
                    ),
                ),
                ("plan", models.CharField(blank=True, max_length=10)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("days", models.PositiveSmallIntegerField(default=0)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("reference", models.CharField(max_length=80, unique=True)),
                ("provider", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("authorization_url", models.URLField(blank=True, max_length=600)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="jobs.employerprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobPostCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("used", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_credits",
                        to="jobs.employerprofile",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credits",
                        to="jobs.jobpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("query", models.CharField(blank=True, max_length=200)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("alert_enabled", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instantly"),
                            ("daily", "Daily digest"),
                            ("weekly", "Weekly digest"),
                        ],
                        default="daily",
                        max_length=8,
                    ),
                ),
                ("notify_push", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=False)),
                ("last_alerted_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobAlertDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(default="push", max_length=10)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_deliveries",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "saved_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="jobs.savedsearch",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["is_searchable", "open_to_work"],
                name="jobs_candid_is_sear_364f94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["country"], name="jobs_candid_country_bfb912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="jobs_msg_thread_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employerprofile",
            index=models.Index(
                fields=["verification_status", "is_active"],
                name="jobs_employ_verific_435045_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofileview",
            index=models.Index(
                fields=["employer", "viewed_at"], name="jobs_cview_emp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["status", "expires_at"], name="jobs_status_expiry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["employer", "status"], name="jobs_employer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["location_type", "status"], name="jobs_loctype_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["employment_type", "status"], name="jobs_emptype_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["country", "status"], name="jobs_country_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["-published_at"], name="jobs_published_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["boosted_until"], name="jobs_boosted_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["featured_until"], name="jobs_featured_idx"),
        ),
        migrations.AddConstraint(
            model_name="joblisting",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("salary_min__isnull", True),
                    ("salary_max__isnull", True),
                    ("salary_min__lte", models.F("salary_max")),
                    _connector="OR",
                ),
                name="jobs_salary_range_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="jobflag",
            index=models.Index(fields=["resolved", "kind"], name="jobs_flag_open_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "status"], name="jobs_app_job_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["candidate", "-created_at"], name="jobs_app_candidate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "status_changed_at"], name="jobs_app_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("job", "candidate"), name="jobs_one_application_per_job"
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["employer", "-last_message_at"], name="jobs_thread_emp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["candidate", "-last_message_at"], name="jobs_thread_cand_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("application__isnull", True)),
                fields=("employer", "candidate"),
                name="jobs_one_direct_thread_per_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="jobpayment",
            index=models.Index(
                fields=["employer", "status"], name="jobs_payment_emp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedjob",
            constraint=models.UniqueConstraint(
                fields=("user", "job"), name="jobs_saved_once"
            ),
        ),
        migrations.AddIndex(
            model_name="savedsearch",
            index=models.Index(
                fields=["alert_enabled", "frequency", "last_alerted_at"],
                name="jobs_alert_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobalertdelivery",
            constraint=models.UniqueConstraint(
                fields=("saved_search", "job"), name="jobs_alert_once_per_job"
            ),
        ),
    ]
