# Generated by Django 5.0.6 on 2026-07-03 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('event_type', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=200)),
                ('signature_valid', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=12)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('wallet_fund', 'Wallet funding'), ('wallet_withdraw', 'Wallet withdrawal'), ('bill', 'Bill payment')], max_length=24)),
                ('provider', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('internal_reference', models.CharField(max_length=80, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=160, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_transactions', to='wallet.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_provider_event'),
        ),
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['user', 'service_type', 'status'], name='payments_se_user_id_4be04f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['provider', 'provider_reference'], name='payments_se_provide_529971_idx'),
        ),
    ]
